package domain

const (
	ORDER_STATUS_PENDING   = "PENDING"
	ORDER_STATUS_CONFIRMED = "CONFIRMED"
	ORDER_STATUS_PREPARING = "PREPARING"
	ORDER_STATUS_READY     = "READY"
	ORDER_STATUS_COMPLETED = "COMPLETED"
	ORDER_STATUS_CANCELLED = "CANCELLED"
)