// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: restaurant.proto

package restaurantpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Restaurant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float32                `protobuf:"fixed32,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Menus         []*MenuItem            `protobuf:"bytes,6,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restaurant) Reset() {
	*x = Restaurant{}
	mi := &file_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restaurant) ProtoMessage() {}

func (x *Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restaurant.ProtoReflect.Descriptor instead.
func (*Restaurant) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *Restaurant) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *Restaurant) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Restaurant) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Restaurant) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Restaurant) GetMenus() []*MenuItem {
	if x != nil {
		return x.Menus
	}
	return nil
}

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *MenuItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuItem) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type RestaurantLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	SecretKey     string                 `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantLoginRequest) Reset() {
	*x = RestaurantLoginRequest{}
	mi := &file_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantLoginRequest) ProtoMessage() {}

func (x *RestaurantLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantLoginRequest.ProtoReflect.Descriptor instead.
func (*RestaurantLoginRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{2}
}

func (x *RestaurantLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RestaurantLoginRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type RegisterRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	SecretKey     string                 `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"` // Of the owner, for authentication purposes
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float32                `protobuf:"fixed32,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Menus         []*RegisterMenuItem    `protobuf:"bytes,6,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRestaurantRequest) Reset() {
	*x = RegisterRestaurantRequest{}
	mi := &file_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRestaurantRequest) ProtoMessage() {}

func (x *RegisterRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRestaurantRequest.ProtoReflect.Descriptor instead.
func (*RegisterRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRestaurantRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRestaurantRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *RegisterRestaurantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRestaurantRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RegisterRestaurantRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RegisterRestaurantRequest) GetMenus() []*RegisterMenuItem {
	if x != nil {
		return x.Menus
	}
	return nil
}

type RegisterMenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMenuItem) Reset() {
	*x = RegisterMenuItem{}
	mi := &file_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMenuItem) ProtoMessage() {}

func (x *RegisterMenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMenuItem.ProtoReflect.Descriptor instead.
func (*RegisterMenuItem) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterMenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterMenuItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterMenuItem) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantRequest) Reset() {
	*x = GetRestaurantRequest{}
	mi := &file_restaurant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantRequest) ProtoMessage() {}

func (x *GetRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{5}
}

func (x *GetRestaurantRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

type ListRestaurantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float32                `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusKm      float32                `protobuf:"fixed32,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRestaurantsRequest) Reset() {
	*x = ListRestaurantsRequest{}
	mi := &file_restaurant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRestaurantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRestaurantsRequest) ProtoMessage() {}

func (x *ListRestaurantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRestaurantsRequest.ProtoReflect.Descriptor instead.
func (*ListRestaurantsRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{6}
}

func (x *ListRestaurantsRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ListRestaurantsRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *ListRestaurantsRequest) GetRadiusKm() float32 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

type AddMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMenuItemRequest) Reset() {
	*x = AddMenuItemRequest{}
	mi := &file_restaurant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMenuItemRequest) ProtoMessage() {}

func (x *AddMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMenuItemRequest.ProtoReflect.Descriptor instead.
func (*AddMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{7}
}

func (x *AddMenuItemRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *AddMenuItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMenuItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddMenuItemRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type RemoveMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMenuItemRequest) Reset() {
	*x = RemoveMenuItemRequest{}
	mi := &file_restaurant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMenuItemRequest) ProtoMessage() {}

func (x *RemoveMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMenuItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveMenuItemRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *RemoveMenuItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type UpdateMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuItemRequest) Reset() {
	*x = UpdateMenuItemRequest{}
	mi := &file_restaurant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemRequest) ProtoMessage() {}

func (x *UpdateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMenuItemRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_restaurant_proto protoreflect.FileDescriptor

const file_restaurant_proto_rawDesc = "" +
	"\n" +
	"\x10restaurant.proto\x12\n" +
	"restaurant\"\xc1\x01\n" +
	"\n" +
	"Restaurant\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x02R\tlongitude\x12*\n" +
	"\x05menus\x18\x06 \x03(\v2\x14.restaurant.MenuItemR\x05menus\"o\n" +
	"\bMenuItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\"M\n" +
	"\x16RestaurantLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tR\tsecretKey\"\xd2\x01\n" +
	"\x19RegisterRestaurantRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tR\tsecretKey\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x02R\tlongitude\x122\n" +
	"\x05menus\x18\x06 \x03(\v2\x1c.restaurant.RegisterMenuItemR\x05menus\"^\n" +
	"\x10RegisterMenuItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\";\n" +
	"\x14GetRestaurantRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\"o\n" +
	"\x16ListRestaurantsRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitude\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x02R\bradiusKm\"\x85\x01\n" +
	"\x12AddMenuItemRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\"U\n" +
	"\x15RemoveMenuItemRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\"\xa1\x01\n" +
	"\x15UpdateMenuItemRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price2\xa4\x04\n" +
	"\x11RestaurantService\x12C\n" +
	"\x05Login\x12\".restaurant.RestaurantLoginRequest\x1a\x16.restaurant.Restaurant\x12S\n" +
	"\x12RegisterRestaurant\x12%.restaurant.RegisterRestaurantRequest\x1a\x16.restaurant.Restaurant\x12I\n" +
	"\rGetRestaurant\x12 .restaurant.GetRestaurantRequest\x1a\x16.restaurant.Restaurant\x12O\n" +
	"\x0fListRestaurants\x12\".restaurant.ListRestaurantsRequest\x1a\x16.restaurant.Restaurant0\x01\x12C\n" +
	"\vAddMenuItem\x12\x1e.restaurant.AddMenuItemRequest\x1a\x14.restaurant.MenuItem\x12I\n" +
	"\x0eRemoveMenuItem\x12!.restaurant.RemoveMenuItemRequest\x1a\x14.restaurant.MenuItem\x12I\n" +
	"\x0eUpdateMenuItem\x12!.restaurant.UpdateMenuItemRequest\x1a\x14.restaurant.MenuItemBMZKgithub.com/tamirat-dejene/ha-soranu/shared/protos/restaurantpb;restaurantpbb\x06proto3"

var (
	file_restaurant_proto_rawDescOnce sync.Once
	file_restaurant_proto_rawDescData []byte
)

func file_restaurant_proto_rawDescGZIP() []byte {
	file_restaurant_proto_rawDescOnce.Do(func() {
		file_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restaurant_proto_rawDesc), len(file_restaurant_proto_rawDesc)))
	})
	return file_restaurant_proto_rawDescData
}

var file_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_restaurant_proto_goTypes = []any{
	(*Restaurant)(nil),                // 0: restaurant.Restaurant
	(*MenuItem)(nil),                  // 1: restaurant.MenuItem
	(*RestaurantLoginRequest)(nil),    // 2: restaurant.RestaurantLoginRequest
	(*RegisterRestaurantRequest)(nil), // 3: restaurant.RegisterRestaurantRequest
	(*RegisterMenuItem)(nil),          // 4: restaurant.RegisterMenuItem
	(*GetRestaurantRequest)(nil),      // 5: restaurant.GetRestaurantRequest
	(*ListRestaurantsRequest)(nil),    // 6: restaurant.ListRestaurantsRequest
	(*AddMenuItemRequest)(nil),        // 7: restaurant.AddMenuItemRequest
	(*RemoveMenuItemRequest)(nil),     // 8: restaurant.RemoveMenuItemRequest
	(*UpdateMenuItemRequest)(nil),     // 9: restaurant.UpdateMenuItemRequest
}
var file_restaurant_proto_depIdxs = []int32{
	1, // 0: restaurant.Restaurant.menus:type_name -> restaurant.MenuItem
	4, // 1: restaurant.RegisterRestaurantRequest.menus:type_name -> restaurant.RegisterMenuItem
	2, // 2: restaurant.RestaurantService.Login:input_type -> restaurant.RestaurantLoginRequest
	3, // 3: restaurant.RestaurantService.RegisterRestaurant:input_type -> restaurant.RegisterRestaurantRequest
	5, // 4: restaurant.RestaurantService.GetRestaurant:input_type -> restaurant.GetRestaurantRequest
	6, // 5: restaurant.RestaurantService.ListRestaurants:input_type -> restaurant.ListRestaurantsRequest
	7, // 6: restaurant.RestaurantService.AddMenuItem:input_type -> restaurant.AddMenuItemRequest
	8, // 7: restaurant.RestaurantService.RemoveMenuItem:input_type -> restaurant.RemoveMenuItemRequest
	9, // 8: restaurant.RestaurantService.UpdateMenuItem:input_type -> restaurant.UpdateMenuItemRequest
	0, // 9: restaurant.RestaurantService.Login:output_type -> restaurant.Restaurant
	0, // 10: restaurant.RestaurantService.RegisterRestaurant:output_type -> restaurant.Restaurant
	0, // 11: restaurant.RestaurantService.GetRestaurant:output_type -> restaurant.Restaurant
	0, // 12: restaurant.RestaurantService.ListRestaurants:output_type -> restaurant.Restaurant
	1, // 13: restaurant.RestaurantService.AddMenuItem:output_type -> restaurant.MenuItem
	1, // 14: restaurant.RestaurantService.RemoveMenuItem:output_type -> restaurant.MenuItem
	1, // 15: restaurant.RestaurantService.UpdateMenuItem:output_type -> restaurant.MenuItem
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_restaurant_proto_init() }
func file_restaurant_proto_init() {
	if File_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restaurant_proto_rawDesc), len(file_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restaurant_proto_goTypes,
		DependencyIndexes: file_restaurant_proto_depIdxs,
		MessageInfos:      file_restaurant_proto_msgTypes,
	}.Build()
	File_restaurant_proto = out.File
	file_restaurant_proto_goTypes = nil
	file_restaurant_proto_depIdxs = nil
}
