// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: envent_envelope.proto

package envent_envelopepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventEnvelope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAtUnix int64                  `protobuf:"varint,2,opt,name=occurred_at_unix,json=occurredAtUnix,proto3" json:"occurred_at_unix,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_envent_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_envent_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_envent_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetOccurredAtUnix() int64 {
	if x != nil {
		return x.OccurredAtUnix
	}
	return 0
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_envent_envelope_proto protoreflect.FileDescriptor

const file_envent_envelope_proto_rawDesc = "" +
	"\n" +
	"\x15envent_envelope.proto\x12\x06common\"n\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12(\n" +
	"\x10occurred_at_unix\x18\x02 \x01(\x03R\x0eoccurredAtUnix\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadBWZUgithub.com/tamirat-dejene/ha-soranu/shared/protos/envent_envelopepb;envent_envelopepbb\x06proto3"

var (
	file_envent_envelope_proto_rawDescOnce sync.Once
	file_envent_envelope_proto_rawDescData []byte
)

func file_envent_envelope_proto_rawDescGZIP() []byte {
	file_envent_envelope_proto_rawDescOnce.Do(func() {
		file_envent_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envent_envelope_proto_rawDesc), len(file_envent_envelope_proto_rawDesc)))
	})
	return file_envent_envelope_proto_rawDescData
}

var file_envent_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envent_envelope_proto_goTypes = []any{
	(*EventEnvelope)(nil), // 0: common.EventEnvelope
}
var file_envent_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_envent_envelope_proto_init() }
func file_envent_envelope_proto_init() {
	if File_envent_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envent_envelope_proto_rawDesc), len(file_envent_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envent_envelope_proto_goTypes,
		DependencyIndexes: file_envent_envelope_proto_depIdxs,
		MessageInfos:      file_envent_envelope_proto_msgTypes,
	}.Build()
	File_envent_envelope_proto = out.File
	file_envent_envelope_proto_goTypes = nil
	file_envent_envelope_proto_depIdxs = nil
}
